### ISSUE TITLE
Hyperlink Fixes

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-web2#2]
**Hyperlink Behavior Changes - The logged-in user should be able to click his own name to view his own profile page. All group names in the newsfeed should be hyperlinked to the group's profile page. Clicking on the group name or avatar when on the group profile page should refresh the group profile page. In the copyright on the right-page, the Powerline text should hyperlink to www.powerli.ne.  
- When I tap on my own large user profile photo (large square) or my name beneath it in the left pane, the system should load the community feed defaulted to All in the central pane (currently, when I tap the large square, it does nothing). 
- When I tap on a group profile avatar (large square) or the group name beneath the large avatar in the left pane, it should open up that group's profile page in the central pane. 
- When I tap on a group profile mini-avatar (small square under My Groups) in the left pane, it should activate the filter for the community feed for that group to that specific group (basically set the drop-down to the same group). 
- When I tap on someone else's name or avatar in the newsfeed, it should open that particular user's profile just like how the user avatar images are hyperlinked currently.
- When I tap on a group name in the newsfeed, it should activate the filter for the community feed for that specific group (set the dropdown to the same group).
- #hashtags and @mentions in the newsfeed should hyperlink. #hashtags open up a search results for the #hashtag and @mentions open up the user profile for that user.

**Comment by icodedaily** [comment]
Cover most of the usecases. Fixed with this commit https://github.com/PowerlineApp/powerline-web2/pull/1. Need to be tested.
