### ISSUE TITLE
Fundraiser UI Amount Field Missing

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-web2#21]
The fundraiser UI is missing the amount for each answer choice. 

There should be one field for the answer choice (e.g. "Medium T-Shirt and Autographed Book") and another field for that answer choice's amount (e.g. "$25). 

Please add second field for amount. See mockup - the blue box is the answer choice (currently exists, good) and the red box is the answer choice amount (does not exist, needs to be added).

![image](https://cloud.githubusercontent.com/assets/7582457/14685188/9798a7a6-0701-11e6-8095-c8080ef7861e.png)

Colors are for reference only

**Comment by solar-dev23** [comment]
Fixed.
