### ISSUE TITLE
Fundraiser UI Crowdfunding Switch Behavior

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-web2#22]
The correct behavior for this element is to show/hide Goal Amount and Goal Deadline fields when "Crowdfunder" label is blue (selected) vs black (not-selected). The Crowdfunder label should toggle between blue and black similar to the "Make Public" label. 

![image](https://cloud.githubusercontent.com/assets/7582457/14685961/c55eb394-0704-11e6-95f8-260d5d7bb15b.png)

**Comment by solar-dev23** [comment]
Fixed.
