### ISSUE TITLE
NG-Letter Implementation

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-web2#3]
The web app should implement the ng-letter-avatar concept that replaces blank avatars with the first initial of the group or user (e.g. G for Google). Similar to Gmail concept. Code to be provided for implementation. 

https://github.com/uttesh/ngletteravatar

**Comment by icodedaily** [comment]
Fixed with this comment merge  https://github.com/PowerlineApp/powerline-web2/pull/7 Need to be tested.
